Added support for different character encodings on read
adamcrume/java-properties pull request #1
Opened 2017-04-21 06:27 UTC by squidpickles

While properties files are generally supposed to be in an ISO-8859-1 encoding, sometimes it makes sense to encode them differently.

For example, we are using them as message sources for various languages. Working entirely with Unicode escape sequences, especially in files with East Asian languages, is cumbersome.

This patch changes the `NaturalLines` iterator to accept an encoding on creation, and then to read bytes into a raw buffer. Decoding only happens on EOL, rather than with each byte; this allows multibyte encodings to work as expected.

Encodings can be specified by calling `PropertiesIter::new_with_encoding()`; using `PropertiesIter::new()` as before will default to `ISO-8859-1` encoding, but with the above behavior change.

2017-04-22 19:32 UTC, adamcrume requested changes

2017-04-22 19:32 UTC, adamcrume commented on src/lib.rs
> +pub struct PropertiesIter<'a, R: Read> {
This is a backward-incompatible change, and I don't want to release 2.0 for just a single commit.  I'll merge this into master, but I'll release a 1.x change that uses `&'static Encoding`.  How does that sound?  If you can find a way to do it without breaking backward compatibility, that's even better.

If we're going to have a breaking change, we might as well make `PropertiesIter` parametric over the type of encoding, i.e. `PropertiesIter<'a, R: Read, E: Encoding + ?Sized>`  Then it can be monomorphized instead of using a trait object.

2017-04-22 19:32 UTC, adamcrume commented on src/lib.rs
> +  fn decode(&self, buf: &Vec<u8>) -> Result<NaturalLine, PropertiesError> {
This should be `&[u8]` instead of `&Vec<u8>`.

2017-04-22 19:32 UTC, adamcrume commented on src/lib.rs
> +  pub fn new_with_encoding(input: R, encoding: &'a Encoding) -> Self {
This should have a warning on it that using an encoding other than ISO 8859-1 is not strictly compliant with the  Java properties file spec, and that most users should call `new` instead.

2017-04-25 17:24 UTC, squidpickles commented on src/lib.rs
> +  fn decode(&self, buf: &Vec<u8>) -> Result<NaturalLine, PropertiesError> {
Ah yes, missed that one. Fixed.

2017-04-25 17:27 UTC, squidpickles commented on src/lib.rs
> +pub struct PropertiesIter<'a, R: Read> {
Depends... would you consider a `Box<Encoding>` in `NaturalLines`? That could also make it possible with no breaking changes.

2017-04-25 17:30 UTC, squidpickles commented on src/lib.rs
> +  pub fn new_with_encoding(input: R, encoding: &'a Encoding) -> Self {
Done.

2017-04-29 21:09 UTC, adamcrume commented on src/lib.rs
> +pub struct PropertiesIter<'a, R: Read> {
That should be fine.

2017-05-02 03:20 UTC, squidpickles commented on src/lib.rs
> +pub struct PropertiesIter<'a, R: Read> {
... I got stuck on `Encoding`'s lack of size, and didn't really want to see `Box<Encoding>` in the API, anyway, so I took your suggestion of `&'static Encoding`.

2017-05-03 02:48 UTC, adamcrume approved these changes

2017-05-03 02:49 UTC, merged